<a href="https://colab.research.google.com/github/julianafalves/Sinais-Digitais/blob/main/Projeto2_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install scikit_dsp_comm

     |████████████████████████████████| 90 kB 8.5 MB/s 


In [2]:
import sk_dsp_comm.sigsys as ss
import numpy as np
from scipy import fftpack
import matplotlib.pyplot as plt
from matplotlib import pylab
from pylab import *

In [3]:
pylab.rcParams['savefig.dpi'] = 100 # default 72
pylab.rcParams['figure.figsize'] = (6.0, 4.0) # default (6,4)
%config InlineBackend.figure_formats=['png'] # default for inline viewing
#config InlineBackend.figure_formats=['svg'] # SVG inline viewing
#%config InlineBackend.figure_formats=['pdf'] # render pdf figs for LaTeX

## Acyclic convolution in matlab

A convolução cíclica, também conhecida como circular, é a convolução de dois sinais de funções periódicas que possuem o mesmo período. Quando são adicionados zeros o suficiente a direita dos sinais sendo convoluídos, é possível conseguir uma convolução acíclica dentro da convolução cíclica.

O calculo calculo da convolução cíclica pode ser realizado diretamente no domínio do tempo ou no domínio da frequência com a FFT (que é mais rápida). Apesar da FFT ser utilizada para convoluções cíclicas é possível utiliza-lá em convoluções acíclicas adicionando zeros á direita do sinal.

In [4]:
# Convolução acíclica
np.convolve([1,2], [3,4])

array([ 3, 10,  8])

In [8]:
#Convolução acíclica como filter primitive
np.convolve([1,2], [3,4], mode='same')

array([ 3, 10])

In [9]:
np.convolve([1,2], [3,4,0], mode='same')

array([ 3, 10,  8])

## Acyclic FFT convolution in matlab

In [10]:
def nextpow2(x):
    return 1 if x == 0 else (x - 1).bit_length()

In [11]:
#realizando a FFT dos sinais x e h
x = [1, 2, 3, 4]
h = [1, 1, 1]

nx = len(x)
nh = len(h)
nfft = 2**nextpow2(nx+nh-1)
xzp = x + [0] * (nfft-nx)
hzp = h + [0] * (nfft-nh)
X = np.fft.fft(xzp)
H = np.fft.fft(hzp)

In [12]:
#Saída das FFT de x e h
print('X:')
print(X)

print('H:')
print(H)

X:
[10.        +0.j         -0.41421356-7.24264069j -2.        +2.j
  2.41421356-1.24264069j -2.        +0.j          2.41421356+1.24264069j
 -2.        -2.j         -0.41421356+7.24264069j]
H:
[3.        +0.j         1.70710678-1.70710678j 0.        -1.j
 0.29289322+0.29289322j 1.        +0.j         0.29289322-0.29289322j
 0.        +1.j         1.70710678+1.70710678j]


In [14]:
Y = X * H # multiplicação dos termos
y = np.real(np.fft.ifft(Y))  #Transformada inversa de Fourier
yt = y[:nx+nh-1]
yc = np.convolve(x,h)  #convolução direta apenas para comparar os resultados

In [15]:
print(yt)
print(yc)

[1. 3. 6. 9. 7. 4.]
[1 3 6 9 7 4]


Um exemplo de implementação da convolução por FFT é em aplicações de filtros FIR de áudio digital. Ele é caracterizado por uma resposta ao impulso que após determinado tempo torna-se nula. Em sua implementação para audio digital, é utilizado  uma largura de banda crítica de audicão que define o termo "tempo de integralização", quando o filtro FIR é menor do que este "tempo de integração" o sinal é pesepctivamente instântaneo.

 O exemplo a seguir exemplifica esta explicação.